[project]
name = "cubs"
version = "0.1.0"
description = "Python Data Science Experiments"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.7",
    "pandas>=2.3.3",
    "requests>=2.32.5",
]

[tool.ruff]
lint.select = [
    # Pyflakes
    "F",
    # Pycodestyle
    "E",
    "W",
    # isort
    "I",
    # flake8-bandit
    "S",
    # flake8-bugbear
    "B",
    # Pylint
    "PL"
]

[dependency-groups]
dev = [
    "ruff>=0.14.8",
]
